"""cascade delete bookings on house delete

Revision ID: d6030a957ddb
Revises: dc3908408232
Create Date: 2026-02-11 16:30:54.101415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6030a957ddb'
down_revision: Union[str, Sequence[str], None] = 'dc3908408232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_house_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'houses', ['house_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_house_id_fkey'), 'bookings', 'houses', ['house_id'], ['id'])
    # ### end Alembic commands ###
